sudo: required
services:
  - docker

before_install:
  - docker build -t stanlee94/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stanlee94/client-test npm run test

after_success:
  - docker build -t stanlee94/mern-client ./client
  - docker build -t stanlee94/mern-nginx ./nginx
  - docker build -t stanlee94/mern-server ./server
  # Log in to Docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stanlee94/mern-client
  - docker push stanlee94/mern-nginx
  - docker push stanlee94/mern-server

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: mern-docker
  env: MernDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-214095551659
  bucket_path: mern-docker-1
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
